[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Jacob Jonsson <jacob.jonsson@schibsted.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "*"
itertools = "0.9.0"